spring:
  datasource:
    url: jdbc:postgresql://database-1.cu1qhm5uej3i.us-east-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "postgres1"
  jpa:
    show-sql: true
    hibernate:
      dl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

### Logging ###
logging:
  level:
    root: ERROR
    #core: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
    org.springframework.web: INFO
    com.iiht.fse4.auth: INFO

### Actuator ###
management:
  endpoint:
    health:
      show-details: "always"
  info:
    git:
      mode: "full"
  endpoints:
    web:
      ## Custom base path for Actuator
      base-path: /actuator
      exposure:
        include: "health,info"

#To be set false to disable swagger UI
springdoc:
  api-docs:
    enabled: true

security:
  crypto:
    secretkey: "$K!11TR@K@R_KEY"
    salt: "$K!11TR@K@R"
  jwt.signing:
    private-key: "-----BEGIN PRIVATE KEY-----MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDCOIvbC107XC6bbG8zWlSc2z2Vbe8EZsINPXDnTUiNN5A/fdQ9mdJr+uBeIXKPD8tBSMvgM9qhVZNa0T8FJWB0htORxe4uKDobZM4O8yFe2efMu0LlVFRCRecRonfOusEoE2637qM9NBGDnk9V+Wpp8bkc5Ewdd9jpOZ8ddfSAccLAgUF+DWLo9o10mEcMcjW7Syaqcx45sArTYVBRQJuvzbnPGgL7vTxRSbDUOYpJ1a5dL8PEkS1dE62X7WM9TQHhQVkVB3Jev4KYVy0HTziCPUpm2TTrsyhsibAOx86KpEQ4j4rgLUC9sNUs7Vf4V04FEwdm4BuVobIXr6b6m719AgMBAAECggEBALA6stw8wYn9KOUqTPRhwGjbnlOafsiVnPp6h5m5TF2mzyJtQEns6zvDVhbTbqlVAW7paOS06Gp/xccgGnjG43CYbhzVZjtHkQIOQ9LY1azFOElSmW6RSCsiVnpv2xof5uhASbRnuoLsXf/5g69VMzOSfA81L8OFXbKx8CjBQOvRt/4LCFVkYqcw7Gaw2eOLSMZCxe5z/SrZHe27MHXSGhP1Q3d5tiMwtsbvSPV0VQjsTkdIANZZQFrm3hinn3fVBU9K8pmr6FN77iMuVMPX3BuiwUCjLtkXIer2yyQKm+MOunv81k8K0RQVdImPMjYhIJRVBG/61KdxewAj425e+1kCgYEA7nEtSG7JTGvxlT+Lb0yM6DtJoUGR8MvXTaEHTnj578/VVk0442PBtWJtrZykISpDNEE57BOkaY2J2RTyQGpXSsZKiUSiqhWkMZvlXPAdlx0L0IAJxyc3yPzgA2UpMLAOBq6I4cZiMMGIwjNKwTjgShgFmJz/FOg+uNtGlwf/+pMCgYEA0IXDr36Ju89gIjMdu6dRXXBjsOtNu8Yj/J0wE2wJrck5v9iTnkJyj1izkDyLyFgXPvyD+axRcl5P6Be+wPuYxAt02nzbjoqKk27aC5fiYD7xsJPVjXxFL5uAbHaOE8KWmGoK/XYww0Zjq2szn+lskYKyAkXfzP1HIrqg7PJzoa8CgYEAjUrtjXVwvWNdlZZBFuPiv56aQ/8p7umrnKmmPb78RDoA7hH2evBbEhPQcEdZDvoPNsDMBPOiwpWHsOZzou4g6gNUmcDdLzKByI/bu1XiAvDIVnX41VWM/gGy8PAaF2rL9POp0zgOaVvVoVZpntQIPH+9mTC3CvmQaVQuoUKxUhcCgYEAwP08Sj0z3oWktKJYf2fwzykIqyJsNEDC57bXWvJf1t7pOtyIay2Wd4Mh1Xmj6Y1WHm54+uf4DYCqNeVcH6H8Fl2ADgMG9VrVvHQZDCfLVUaMS9/XAvaj1db2uevTvQgYdwGWIFV19hU8g9dY1USlvdqXQ7FF26QCZWsTK5mNWXMCgYABF2JdV99N4F1kbwBTmwpER0AINOz09KDOBbW7yPeIKFkBFonhHpyigmUR+e7ipid/6FtP01RVVxywwFvJDhtvUDli4ZcZQyPI4b+RAF6ceZUXlf0Kuh4RFr5lI1Q9lWOoHN24Z7JkI6cqL3QuLez8jnRoqjduqi8WHHHSUO+Skg==-----END PRIVATE KEY-----"
    public-key: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwjiL2wtdO1wum2xvM1pUnNs9lW3vBGbCDT1w501IjTeQP33UPZnSa/rgXiFyjw/LQUjL4DPaoVWTWtE/BSVgdIbTkcXuLig6G2TODvMhXtnnzLtC5VRUQkXnEaJ3zrrBKBNut+6jPTQRg55PVflqafG5HORMHXfY6TmfHXX0gHHCwIFBfg1i6PaNdJhHDHI1u0smqnMeObAK02FQUUCbr825zxoC+708UUmw1DmKSdWuXS/DxJEtXROtl+1jPU0B4UFZFQdyXr+CmFctB084gj1KZtk067MobImwDsfOiqREOI+K4C1AvbDVLO1X+FdOBRMHZuAblaGyF6+m+pu9fQIDAQAB-----END PUBLIC KEY-----"
